local module = {}
module["Honored One"] = function()
return [[
ipasapipas
apipasapip
asapuoa[sk]a
ouoadaouoa
[dk]aouoafao
yps[hk]spyps
hspyps[hk]sp
ypshsptof
[kz]fotofkfo
tof[kz]fotof
lfo[iz]p[aj]s
[ak]p[il]pasa
p[iz]p[aj]s[ak]
p[il]pa[sk][aj]
p[uz]o[ah]s[aj]
o[uk]oadao
[uz]o[ah]f[aj]o
[uk]oa[fj][ah]o
[yz]p[sh]h[sj]p
[yk]pshsp[yz]
p[sh]h[sj]p[yk]
ps[hj][sz]p
[thv]o[gc]h[gz]
o[tk]odhdoto
fkkfo[tkz]of
[klv]fo[4l]80s
[ef]f[qf]typ
[ed]f[qh]tup
[td]p[qs]tuoy
15[8hk][0l][rk]
w[8of]wru[rd]w
[8od]wry[uf]
[yh][uh]tyost
[fhlq]eEiz[tlh]
Estf[qd][9ph]q
et[dg]0[qsf]et
uoy[wu]t[yfk]
[tl][yk]odaty
d[0s]eyouwr
[uf][ok][pzv]ti
pfbggbf[gb]
[ps]jbklbk
[hm][sfv]vxdvv
z[4sfl]80e0dh
khgd[adz]oiy
r[fx]9[4fx]80o
ao[8lm][wkn]e
[fx]q[dz][1ahk]5
[8a][0s][wa][yo]
[8y]w[rgjc]y
[fhx][7dgz]qery
x[3sl]79WtOs
Ot[toa6]0[esl]e
[tdz]u[efjlx]t
[kno]r[lmt]9
[5hlv]9wrth
[wl][yh][ol]crx
[4ljx]8qwe[tx]
[qjz][tl]iwel
[2jv]690qe
[9vn][qk][ex][tb]
[0v][qs][6lbm]80
[wsf]etqw[tf]h
ze[wk]q[7ofh]0
wruo[wa]ufhk
[qm]un[am]vsm
hgf[tm]uOnm
[sv]mdmva
]]
end
module['The World'] = function()
return [[
[%370] 3 3 3 3 3 3 3 3 3 3 [3wru] 3 3 3 3 3 3 3 [O3af]
[O3af] [Oaf] 3 [pj] [sl] [dz] [6fjlx]
[efjlx] [tufjlx] e [phv] [ugc] t [5fhkx]
[wfhkx] [ryfhkx] w [odz] [yfx] r [4sfjl]
[qsfjl] [etsfjl] q [isl] [tdz] [efx] [3fx]
[0dz] [Wr] 0 [%y] r [%W] [6fjlx]
[efjlx] [tufjlx] [efx] [phv] [ugc] t [5fhkx]
[wfhkx] [rydz] w [osl] [yak] r [4sfjl]
q [et] [qak] [isl] t [egc] [H3fkx]
y r W 0 7 [3ep] [ts] [3yd] [6upsf]
[7upsf] [8upsf] [6uf] [eoh] [0ig] 8 [5uoaf]
[6uoaf] [7yd] 5 [wts] [9ra] 7 [4tups]
[5tups] [6ts] 4 [qyd] [8uf] 6 [O3rua]
W 0 7 [%ep] [ts] [%yd] [6upsf]
[7upsf] [8upsf] [6uf] [eoh] [0ig] 8 [5uoaf]
[6uoaf] [7yd] 5 [wts] [9ra] 7 [4tups]
[5tu] [6tu] 4 [qtu] [8ra] [6ts] [3ig]
[WOruaf] [Wr] 0 [Wrig] 0 7 3 [6upsf]
6 [0etu] 6 o 6 [0etu] [6p]
[6p] [0etu] 6 [8o] 7 [5tu] [4p]
4 [8etu] 4 o 4 [8etu] [4p]
[4p] [8etu] 4 [5o] 6 [4tu] [18tuos]
8 [0wtu] 8 o 8 [0wtu] [18s]
[8s] [0wtu] 8 o 1 [2d] [O3yua]
3 [W7y] 3 u 3 [W7y] [O3ua]
[3a] [W7y] 3 [ru] [WO] [0a] [7d] [3f] [6sfj]
6 [0sf] e [rh] t [esf] [pj]
u [tj] [rsf] e [6h] 6 [5sf] [4sfj]
4 [8sf] q [wh] e [qsf] [ij]
t [ej] [wsf] q [4h] 4 [4sf] [18sfhl]
8 [wsf] t [yh] u [tsf] [sl]
o [ul] [ysf] t [1h] 8 [29dz] [30adfk]
0 [ead] r [yf] u [rad] [Ok]
u [yk] [%Wad] 0 [6ef] 0 [7rad]
[60ep] s f [60e] j [5w] [5w] [48q]
q t i [psg] [6e]
[tufx] e [dz] e [tusl] e
[ak] e [tupj] e [ak] e [tusl] [4qdgjz]
q [eti] q q [etisl] [qak]
q [eti] q q [eti] [6e]
e [tupj] e [pj] e [tupj] e
[sl] e [tupj] e [sl] e [tudz] [5wadk]
w [ry] w w [rypj] [woh]
[wd] [rya] [wo] y r w [60e]
6 [tfjlx] 6 [edz] 6 [0tsfl] [60e]
k 6 [tsfj] 6 [ek] 6 [0tsfl] [48qdgjz]
4 [esg] 4 q 4 [8esgl] [48qk]
4 [esg] 4 q 4 [8eak] [18sfhl]
8 [0wtsfh] 8 0 8 [0wtsfh] [18]
l 8 [0wtak] 8 [sfhl] [18] [29dz] [H30fk]
0 [WHrydf] 0 W 0 [WHrydf] [30]
[sl] 0 W 0 [Hydfkz] r W 0 7 3
[4fjlx] u p [qetf] u [4p] [4f]
u [qp] f [qu] [etp] f [qu] p
5 u p [wryf] u [5p] [5f]
u p a w f j k x w b k [ryx]
4 [et] q [fjlx] q [et] q
[dgjz] q [et] q [sghl] q [et] [18sfhl]
8 [0wf] 8 d 8 [0ws] [8s]
8 [0w] 8 1 [sl] [2ak] [OH3a]
3 [W7] 3 [OHa] 3 [W7] 3
[pj] 3 [W7] 3 [%dfkz] 0 W [6dfjz]
6 [0t] 6 [sfl] 6 [0tak] [6sfl]
[6pj] [0oh] [18uf] [YD] [8yd] [0wts] [4etip]
4 [8e] 4 [fjlx] 4 [8e] 4
[dgjz] 4 [8e] 4 [fjlx] 4 [8e] [18hlxv]
8 [0w] 8 [yd] 8 [0wts] [8oh]
8 [0wdz] 1 [sl] 1 [2dz] [H3fk]
3 [W7] 3 [ep] 3 [W7ra] [WO3]
3 [W7ak] 3 [7sl] 0 [Wdz] [H3fkx]
[Oy] [ra] [Wd] [0f] [7g] [3d] [O3af]
[O3af] [O3af] [pj] [sl] [dz] [6fjlx]
[efjlx] [tufjlx] e [phv] [ugc] t [5fhkx]
[wfhkx] [ryfhkx] w [odz] [yfx] r [4sfjl]
[qsfjl] [etsfjl] q [isl] [tdz] [efx] [3fx]
[0dz] [Wr] 0 [%y] r [%W] [6fjlx]
[efjlx] [tufjlx] [efx] [phv] [ugc] t [5fhkx]
[wfhkx] [rydz] w [osl] [yak] r [4sfjl]
q [et] [qak] [isl] t [egc] [H3fkx]
y r W 0 7 [3ep] [ts] [3yd] [6upsf]
[7upsf] [8upsf] [6uf] [eoh] [0ig] 8 [5uoaf]
[6uoaf] [7yd] 5 [wts] [9ra] 7 [4tups]
[5tups] [6ts] 4 [qyd] [8uf] 6 [O3rua]
W 0 7 [%ep] [ts] [%yd] [6upsf]
[7upsf] [8upsf] [6uf] [eoh] [0ig] 8 [5uoaf]
[6uoaf] [7yd] 5 [wts] [9ra] 7 [4tups]
[4tups] [5tu] [6tu] 4 [qtu] [8ra] [6ts] [3ig]
[WOruaf] [Wr] 0 [Wr] s [3a] [4tup]
4 [8tu] 4 [7tup] 6 [4f] [5yoad]
5 [9yoad] 5 [8yos] [7a] 5 [6tup]
6 [0tu] 6 [9tus] 8 [6s] [5yoad]
5 [9yoa] 5 [8yoa] 7 [5o] [4tup]
[4p] [8tup] 4 [7ts] 6 [4uf] [3yuad]
[oh] [ig] [6upsf]
6 [0u] p [ea] f [rj] [tkx] [ef] [tj]
[pkx] [uf] [tj] [ejkx] 6 [dz] [5sl] [4sfk]
[4l] [8k] [qsfh] w [ej] [qh] [tpsg]
i t [ec] l [qj] g [4s] p i t e [4q] [18tus]
[5tus] [8ra] 9 [0ts] [wyd] 8 [tuf]
w [0o] s [7d] f h l z [18v] x [29z] l h [30tus]
[7tus] [9ra] 0 [ets] [rpj] 0 [OHua]
r [WO] a [%Wd] f H k x [V6e] x [7rz] k H [6psfj]
[6j] [0b] x [ez] x [rl] x [tb] x [uz] x [el] x
[pb] x [uz] x [tl] x [rb] [6j] k [el] x [0b] [4osfh]
[4h] [8v] l [qk] l [wj] l [ev] l [tk] l [qj] l
[iv] l [tk] l [ej] l [wv] [4h] j [qk] l [8v] [18uof]
[8o] s [wd] f h t l z [yx] [uc] [oz] [thlx]
s [oc] x [uz] [tl] [18z] k [29l] [30pdgj]
7 0 e r y i p [ak] [0pj] [WOruaf]
0 [Hyafk] r W 0 [7sl] 3 [7dz] 0
[60efjlx] [60e] f [5wjl] x f [60ejl] [60ex]
f [5wjl] x f [60efjlx] [dz] [sl] [ak]
[60epsfj] [60e] p [5wsf] j p [60esf] [60ej]
p [5wsf] j p [60eoh] [pj] [sl] [fx]
[6hlxv] 6 h [5lx] v h [6lx] [6v]
h [5lx] v h [6v] x l h f s o
[6lxv] h l [5lxv] h l [4hlxv] [jlxb]
4 8 q w e t u p s
f 4 4 4
4 [et] q [ipf] q [et] q
d q [et] q s q [et] [18uos]
8 [0wfx] 8 [dz] 8 [0wsl] [8sl]
8 [0w] 8 1 s [2a] [O3yu]
3 [W7] 3 O 3 [W7] 3
p 3 [W7] 3 [%Oud] 0 W [6upd]
6 [0t] 6 s 6 [0ta] [6s]
[6jb] [0hv] [18fx] [DZ] [8dz] [0wsl] [4psgj]
4 [8e] 4 [ipf] 4 [8e] 4
d 4 [8e] 4 f 4 [8e] [18osfh]
8 [0w] 8 [dz] 8 [0wsl] [8hv]
8 [0wyd] 1 [ts] 1 [2yd] [O3ua]
3 [W7] 3 [pj] 3 [W7ak] [OH3]
3 [W7ra] 3 [7ts] 0 [Wyd] [O3uaf]
[OHy] [rak] [Wdz] [0fx] [7gc] [3dz] [H3fkx]
[Hfkx] [H3fkx] [H3fkx] [O3uaf]
[O3uaf] [O3uaf] e t y [etux]
j [ul] [ux] [ej] [ol] [ix] j [wrux]
h [uk] [ux] [wh] [yk] [ux] h [qetx]
j [tl] [tx] [qj] [tl] [yx] [uj] [W0rux]
H [yk] x H [0x] k f [etux]
j [ul] [ux] [ej] [ol] [ix] j [wrux]
h [uk] [yx] [wh] [tk] [rx] h [qetx]
j l x [rj] [tl] x [ij] [W0rux] k
H f a O [0u] 3 [ep] [ts] [yd] [6upsf]
[7upsf] [8upsf] [6uf] [eoh] [0ig] 8 [5uoaf]
[6uoaf] [7yd] 5 [wts] [9ra] 7 [4tups]
[5tups] [6ts] 4 [qyd] [8uf] 6 [O3rua]
W 0 7 [%ep] [ts] [%yd] [6upsf]
[7upsf] [8upsf] [6uf] [eoh] [0ig] 8 [5uoaf]
[6uoaf] [7yd] 5 [wts] [9ra] 7 [4tups]
[5tu] [6tu] 4 [qtu] [8ra] [6ts] [3ig]
[WOruaf] [Wr] 0 [Wr] s [3a] [4tup]
4 [8tu] 4 [7tup] 6 [4f] [5yoad]
5 [9yoad] 5 [8yos] [7a] 5 [6tup]
6 [0tu] 6 [9tus] 8 [6s] [5yoad]
5 [9yoa] 5 [8yoa] 7 [5o] [4tup]
[4p] [8tup] 4 [7ts] 6 [4uf] [3yuad]
3 7 [90ry] 7 3
y r 0 9 7 3 3 [oh] [ig] [6ig]
[6upsf] 0 6 [9uo] [8p] 7 [5upsf]
[5u] [0up] 5 [9uo] [8p] 7 [4upsf]
[4u] [0up] 4 [9uo] [8p] 7 [3upsf]
3 [79up] 3 [WOHaf] 3 [O7] [6psfj]
[6p] [0sf] 6 [9ad] [8sf] 7 [5psfj]
[5p] [0sf] 5 [9ad] [8sf] 7 [4psfj]
[4p] [0sf] 4 [9ad] [8sf] 7 [3psfj]
[3p] [79sf] 3 [WHfk] [3a] [7f] [6fjlx]
[6u] [0upsf] 6 [9yad] [8upf] 7 [5fjlx]
[5u] [0upsf] 5 [9yad] [8upf] 7 [4fjlx]
[4u] [0upsf] 4 [9yad] [8upf] 7 [3fjlx]
[3u] [79upsf] 3 [WHVkx] 3 [H7] [6jlxb]
[6p] [0psfj] 6 [9oah] [8pfj] 7 [5jlxb]
[5p] [0psfj] 5 [9oah] [8pfj] 7 [4jlxb]
[4p] [0psfj] 4 [9oah] [8pfj] 7 [3jlxb]
[3p] [79psfj] 3 [WHV] x k 3 H f [7a] 3
[6jlxb] 6 5 5 [qtopf] h j x
]]
end
module['Tokyo Ghoul'] = function()
return [[
J l-J-j h-
l-J-j-h-
h g--D D-g 
d----
d [(d]-d d ( z z-
w--w--
J [jq]-j j q J J-
9--9--
J [(^l]-J-[(^j] h-
l [9w] J-j [9w] h-
h [8gq]--D [8Dq]-g 
d [^9]--[^9]--
d [(^d]-d d [(^] z z-
[9w]--[9w]--
J [8jq]-j j [8q] J J-
[5w]----
d-s-P d-s-
P [5w][5w] [5w] [5w][5w] [5w][5w] [5w][5w]-
[dw]J d[hq] d ( d [9s]d-
[dw]J d[hq] d ( J 9j-
[dw]J d[hq] d ( d [9s]d-
[dw]J d[hq] d ( J Qj-
E-w-t E-w-
[pt] [Py]-P-[Pt]--P 
d [dq]-s-s--
P [qs]-P-[pt]-i-
y t--E--
i [Ei] y[ey]-[ey] [Et] y[ey]-
[ei] [Ei] y[ey]-[ey] [Et] y[ey]-
[ei] [Ei] y[ey]-[Ey] [et]-[Ey]-
[Ey]--y d-s 
s [(@^d]-s s s-P-
p [48q] P-p-i-
i [59dw]-s s-P-
P [269p]-P-g-p-
P [(@^h]-g d-P-
P [48Pq]-p o-p-
P [59w]----
J [269j]-J-j-g-
i [(@^d] ss-s s PP-
P [48pq]-P-p-i-
i [59dw] ss-s s PP-
P [269p]-P-g-p-
P [(@^h]-g d P--
P [48Pq]-p o-p-
P [59w]----
]]
end
module['Another Love'] = function()
return [[
[9ey]-[pdg] [ey] o [osfh] [ey] [sgj]
[qti] g s [yiEP] d [dgPJ] [yi] [pdgj]
[9ey]-[pdg] [ey]-[pdh] y [upsf]
[60e]-[upsf] [et]-[sg] [et] [Pyd]
[9q^E]-[dgJ] [9qE] o [osfh] E [pdgj]
[9ey] g d [wyEP] d [dgJ] [Ey] [pdgj]
[9ey]-[pdg] [yi]-[pdh] [yi] [upsf]
[60e]-[upsf] [et]-[sg] [et] [yiP]
[q^E]-y [qE]-y q E
[^q] E y q E y q E
[^9q] i i i i-o p
[9qe] i-i [wEP] P-p
[9qe]–i i o-u
[680e]-u y u i-y
[^9q]–i i-o p
[9qei] i-i [wEP] P-p
[9qe]–i i o-u
[680e]-u y u i–
[^q] y-q E P q y
^–q E P q y
[^9q]-i [qi] i o q [yp]
[9qe] i i [5wi] [yP] [yP] w [ip]
9-y [9i] i [yo]-[tu]
6 e t [0u] [6tu] [eti]-[Ey]
^ q y [qi] [Ei] [uo] 8 [ip]
9 y [ep] [wp] [iP] [yP] w [ip]
9-y [ep] p [yip] [9q] [tuo]
6-[et] [0o] o [etp] 0 E
^-[Ei] q-[Ey] q E
[^q]-E q-[Ey] q E
[^Eqyi]-p p p P p-
[qeti]–p p P p-
[9eyi]–p P-s
[60etu]–p p P-p
[^Eqyi]-p p p P p-
[qeti]–p p P p-
[9eyi]–p P-s
[60etu]–p p P-p
[^Eqyi]-[ps] [ps] [ps] [Pd] [ps]-
[4q]-t [ips] [ps] [Pd] [yps]-
[9qyip]-y [9q] [ep] [iP] [9q] [ts]
[60e]–[eP] [tp] [uP] E-
[^Eqyp]–i–
[4qet]—-
[29eyip]—-
[6etuo]—-
[29]-[29dg] p [29] [osfh] [29] [psgj]
[4q] g [4qs] P [^d?] [dgPJ] [^?] [pdgj]
[29]-[29dg] p [29pdg] [pdh] [29] [upsf]
6-[6usf] p [6usf] [isg] 6 [Pyd]
[^?]-[dg^J?] P [^o?] [osfh] [18] [pdgj]
[29] g [29d] [yiP] [^?] [dgPJ] [^?] [pdgj]
[29]-[29pd] p [29pdg] [pdh] [29] [upsf]
6-[6usf] p [6usf] [isg] 6 [yiP]
[^?]-[^y?] E [^?] [iP] [^?] y
[^E?]-[^y?]-[^E?] i [^?] [Ey]
[^?] E [^Eyi?] [Eyi] [^Eyi?] [ti] [18o] [eyp]
[29] [ei] [29] [yi] [5yoP] [yoP] 5 [eyp]
[29] e [29yi] [wo] [29wo]-[29yo] [tu]
6 [eu] [6eu] [ey] [6eu] [eti] 6 [Ey]
[^?] E [^Eyi?] [Eyi] [^Eyi?] [tuo] [18] [eyp]
[29] [ep] [29ep] [ep] [5yoP] [yoP] 5 [eyp]
[29] e [29yp] [yp] [29yp] [yp] [29] [tuo]
6 e [6eto] [eto] [6eto] [eto] 6 [Eyi]
[^?] E [^Eyi?] [Eyi] [^Eyi?] [tuo] [^?] [eyp]
[29] [ep] [29ep] [yoP] 5 [yoP] 5 [eyp]
[29] e [29ep] [ep] [29ep] [yp] [29] [tuo]
6 e [6eto] [eto] [6eto] [etp] 6 [Eyi]
[^?] E [^Eyi?] [Eyi] [^Eyi?] [tuo] [18] [eyp]
[29] [ep] [29ep] [ep] [5yoP]-[E5o] [yp]
[29] e [29y] [ep] [29ep] [yp] [29] [etuo]
6 e [6eo] [eo] [6eo] [etp] 6 [Eyi]
[^?]-[^Eyp?] [Eyp] [^Eyp?] [yEP] [^Eyp?]-
4 e [4t] [tip] [4tip] [tiP] [4tip]-
[29ey] e [29yi]-[29ep] [yiP] [29] [tus]
6 e [6tu] e [6tup] [tuP] 6 [Eyp]
[^?]-[^Eyp?] [Eyp] [^Eyp?] [yEP] [^Eyp?]-
4 e [4t] [tip] [4tip] [tiP] [4tip]-
[29ey] e [29yi]-[29ep] [yiP] [29] [tus]
6 e [6tu] e [6tup] [tuP] 6 [Eyp]
[^?]-[^yps?] [yps] [^yps?] [Pyd] [^yps?]-
4 e [4t] [ips] [4ips] [Pid] [4ips]-
[29ey] e [29yi]-[29ep] [yiP] [29] [tus]
6 e [6tu] [ep] [6tup] [tuP] 6 [Eyip]
[^?] E [^y?] E [^yi?] E [^y?] E
[4t]-[4ti] e [4ti] e [4ti] e
[29yip] e [29yip] e [29yip] e [29yip] e
[6tuo] e [6tuo] e [6tuo] e [6tuo] e
[^Eyi?]-[dg^J?] P [^?] [osfh] [18] [pdgj]
[29] [pdg] [29pd] [dhPJ] 5 [dhPJ] 5 [pdgj]
[29] p [29pdg]-[29p] [pdh] [29] [upsf]
6-[6upsf] p 6 [ipsg] 6 [dgJ]
[^?]-[dg^J?] P [^?] [osfh] [18] [pdgj]
[29] [pdg] [29pd] [dhPJ] 5 [dhPJ] 5 [pdgj]
[29] p [29pdg]-[29p] [pdh] [29] [upsf]
6-[6upsf] p 6 [ipsg] 6 [dgJ]
[^?] [Pyid] [^Pyid?] [Pyid] [^Pyid?] [uosd] [18] [yipd]
[29]-[29yipd] [yips] [P5yod] [Pyod] 5 [yipd]
[29]-[29yipd] [yipd] [29yip] [yipd] [29] [tups]
6-[6upsf] [upsf] [6upsf] [upsf] 6 [Pyid]
[^?]-[^Pyid?] [Pyid] [^Pyid?] [uosd] [18] [yipd]
[29] [yipd] [29yipd] [yips] [P5yod]-[P5yod] [yipd]
[29]-[29] [yipd] [29yipd] [yipd] [29] [tups]
6-6 [ups] [6upsf] [ipsg] 6 [Pyid]
[^?]-[^Eyp?] [Eyp] [^Eyp?] [yEP] [^Eyp?]-
4 e [4t] [tip] [4tip] [tiP] [4tip]-
[29ey] e [29yi]-[29ep] [yiP] [29] [tus]
6 e [6tu] [ep] [6tup] [tuP] 6 [Eyp]
[^?]-[^Eyp?] [Eyp] [^Eyp?] [yEP] [^Eyp?]-
4 e [4t] [tip] [4tip] [tiP] [4tip]-
[29ey] e [29yi]-[29ep] [yiP] [29] [tus]
6 e [6tu] [tps] [6tups] [tups] 6 [ypd]
[^?]-[^ypd?] [yps] [^ypd?] [yps] [^yps?]-
4 e [4t] [ypd] [4ypd] [yps] [4yps]-
[29ey] e [29yi]-[29ep] [yiP] [29] [tus]
6 e [6tu] [ep] [6tup] [tuP] 6 p
[^Eey?]–i–
[4qet]—-
[29eyip]—-
[6etuo]
]]
end
module['Rush E'] = function()
	return [[
u----
u----
u----
u----
u--u--
u--u--
u-u-u-u-
u u u u u u u [fu] 
[0fu] [03fx] [03fx] [03fx] [3x] [3x] [3x] [3x] 
[6]-[08]-3-[08]-
[6]-[08]-3-[08]-
[6u] u [08u] u [3u] u [08u] u 
[6u] u [08u] u [3u] u [08u] u 
[6u] u [08u] u [3u] i [08u] Y 
[6u]-[08p]-[3s]-[08]-
[%d] d [09d] d [3d] s [09a] d 
[6s] s [08s] s [3s] a [08p] s 
[7a] a [(ar] a [$I]-[(ae]-
[0O]--[03]--$5%
[6u] u [08u] u [3u] u [08u] u 
[6u] u [08u] u [3u] u [08u] u 
[6u] i [08u] Y [3u]-[08p] s 
[6f]-[08j]-[3l]-[08]-
[9z] l [kqr] z [8l] k [0jt] l 
[7k] j [9HW] k [6j] f [8es] p 
[03g] f [$dQ] s [%aW] p [03O] a 
[6ep]--[3]--$5%
[6u] u [08u] u [3u] u [08u] u 
[6u] u [08u] u [3u] u [08u] u 
[6u] u [08u] u [3u] i [08u] Y 
[6u]-[08p]-[3s]-[08]-
[%d] d [09d] d [3d] s [09a] d 
[6s] s [08s] s [3s] a [08p] s 
[7a] a [(ar] a [$I]-[(ae]-
[0O]--[03]--$5%
[6u] u [08u] u [3u] u [08u] u 
6 u [08u] u [3u] u [08u] u 
[6u] i [08u] Y [3u]-[08p] s 
[6f]-[08j]-[3l]-[08]-
[9z] l [kqr] z [8l] k [0jt] l 
[7k] j [9HW] k [6j] f [8es] p 
[03g] f [$dQ] s [%aW] p [03O] a 
[6ep]--[6]--78*
[29d]-[eq] S [6d]-[efq]-
[9g]-[efq]-[6d]-[egq]-
[8f]-[0e] d [6s]-[0de]-
[8f]-[0e]-6-[0es]-
[7a]-[9W] P [3a]-[9sW]-
[7d]-[9sW]-[3a]-[9dW]-
[18s]-[6p]-[18s]-[03f]-
[6ej]-f-[6s]-p-78*
[29d]-[eq] S [6d]-[efq]-
[9g]-[efq]-[6d]-[egq]-
[8f]-[0e] d [6s]-[0de]-
[8f]-[0e]-[6j]-[0e]-
7-[deq]-9-[egq]-
[%03f]-[18s]-[29d]-[7a]-
[6p]----[03afOu]-
[06efjps]----
[6u] u [08u] u [3u] u [08u] u 
[6u] u [08u] u [3u] u [08u] u 
[6u] u [08u] u [3u] i [08u] Y 
[6u]-[08p]-[3s]-[08]-
[%d] d [09d] d [3d] s [09a] d 
[6s] s [08s] s [3s] a [08p] s 
[7a] a [(ar] a [$I]-[(ae]-
[0O]--[03]--$5%
[6u] u [08u] u [3u] u [08u] u 
6 u [08u] u [3u] u [08u] u 
[6u] i [08u] Y [3u]-[08p] s 
[6f]-[08j]-[3l]-[08]-
[9z] l [kqr] z [8l] k [0jt] l 
[7k] j [9HW] k [6j] f [8es] p 
[03g] f [$dQ] s [%aW] p [03O] a 
[6ep]--[!(@*%^$148abcdEfghiIjklmnoOpPqQstTuvWxyYz]--
6-[08]-3-[08]-
6-[08]-3-[08]-
6-[08]-3-[08]-
6-[08]-3-[08]-
6-[08e]-3-[08e]-
6-[08e]-3-[08e]-
6-[08t]-3-[08t]-
6-[08t]-3-[08t]-
6-[etu]-3-[etu]-
6-[etu]-3-[etu]-
6-[ptu]-3-[ptu]-
6-[stu]-3-[stu]-
[6u] u [etu] u [3u] u [eftu] f 
[6x] x [eftu] f [3u] u [etu] u 
[6u] u [etu] u [3u] i [etu] Y 
[6u]-[eptu]-[3s]-[etu]-
[%d] d [09dW] d [3d] s [09aW] d 
[6s] s [estu] s [3s] a [eptu] s 
[7a] a [(ar] a [$I]-[(ae]-
[0O]--[03]--$5%
[6u] u [etu] u [3u] u [etu] u 
6 u [etu] u [3u] u [etu] u 
[6u] i [etu] Y [3u]-[eptu] s 
[6f]-[ejtu]-[3l]-[etu]-
[9fkz] l [kqr] z [8fjl] k [0jt] l 
[7Hk] j [9HW] k [6fj] f [8es] p 
[03g] f [$dQ] s [%aW] p [03O] a 
[6ep]----
[29d]-[eq] S [6d]-[efq]-
[9g]-[efq]-[6d]-[egq]-
[8f]-[0e] d [6s]-[0de]-
[8f]-[0e]-6-[0es]-
[7a]-[9W] P [3a]-[9sW]-
[7d]-[9sW]-[3a]-[9dW]-
[18s]-[6p]-[18s]-[03f]-
[6ej]-f-[6s]-p-78*
[29d]-[eq] S [6d]-[efq]-
[9g]-[efq]-[6d]-[egq]-
[8f]-[0e] d [6s]-[0de]-
[8f]-[0e]-[6j]-[0e]-
7-[deq]-9-[egq]-
[%03f]-[18s]-[29d]-[7a]-
[6p]----[03afOu]-
[06efjps]----
[6u] u [etu] u [3u] u [eftu] f 
[6x] x [eftu] f [3u] u [etu] u 
[6u] u [etu] u [3u] i [etu] Y 
[6u]-[eptu]-[3s]-[etu]-
[%d] d [09dW] d [3d] s [09aW] d 
[6s] s [estu] s [3s] a [eptu] s 
[7a] a [(ar] a [$I]-[(ae]-
[0O]--[03]--$5%
[6u] u [etu] u [3u] u [etu] u 
6 u [etu] u [3u] u [etu] u 
[6u] i [etu] Y [3u]-[eptu] s 
[6f]-[ejtu]-[3l]-[etu]-
[9fkz] l [kqr] z [8fjl] k [0jt] l 
[7Hk] j [9HW] k [6fj] f [8es] p 
[03g] f [$dQ] s [%aW] p [03O] a 
[6ep]----
[^i] i [EiT] i [4i] i [EiT] i 
[^i] i [EiT] i [4i] i [EiT] i 
[^i] i [EiT] i [4i] I [EiT] u 
[^i]-[EiPT]-[4S]-[EiT]-
[6D] D [(Deq] D [4D] S [(eqs] D 
[^S] S [EiST] S [4S] s [EiPT] S 
[8s] s [0st] s [5o]-[0Es]-
[pq]--[4q]--5%6
[^i] i [EiT] i [4i] i [EiT] i 
^ i [EiT] i [4i] i [EiT] i 
[^i] I [EiT] u [4i]-[EiPT] S 
[^g]-[EiJT]-[4L]-[EiT]-
[(Z] L [lQt] Z [*L] l [JqT] L 
[8l] J [(jW] l [^J] g [*ES] P 
[4Gq] g [5Dw] S [6es] P [4pq] s 
[^EP]----
[IsYZ] L l Z [iLPT] l J L 
[lptY] J j l [EJPT] g S P 
[4Gq] g [5Dw] S [6es] P [4pq] s 
[^EP]--[^gJS]
]]
end

module['La Distancia'] = function()
	return [[
[06]0etute[9q]eyi[03]rW
[06]0etute[9q]eyi[03]rW
[6u]t[etw]u[5t][%e]u[6t]i[tw]ei[5t]e[%i]t
[6u]t[etw]u[5t][%e]u[6t]i[tw]ei[5t]e[%i]t
[6u]t[etw]u[5t][%e]u[6t]i[tw]ei[5t]e[%i]t
[6u]t[etw]u[5t][%e]u[6t]i[tw]ei[5t]e[%i]t
[6i]u[twy]u[5y][%t]y[6t][Ei][etw]E[it][5y]u[%i] 
[6u]t[etw]u[5t][%e]u[6t]i[tw]ei[5t]e[%i]t
[6i]u[twy]u[5y][%t]y[6t][Ei][etw]E[it][5y]u[%i] 
[6u]t[etw]u[5t][%e]u[6t]i[tw]ei[5t]e[%i]t
[0eu][Et][e][uw][et][eE][eu][tw][ei][Et][e][iw][et][eE][ei][tw]
[eu][Et][e][uw][et][eE][eu][tw][ei][Et][e][iw][et][eE][iy][it]
[Eiqu][it][eu][uy][tu][ei][u][ty][iu][it][eu][iy][tu][ei][iu][ty]
[u][it][eu][uy][tu][ei][u][ty][iu][it][eu][iy][ot][ei][iu][ty]
[otuw][it][eu][uy][tu][ei][u][ty][iu][it][eu][iy][tu][ei][iu][ty]
[ou][it][eu][uy][it][eu][uy][t][iu][ty][et][Ei][ty][et][Ei][et]
[Eiqtu][Et][e][uw][Et][e][uw][qt][ei][tw][eq][0i][tw][eq][0i][9t]
[0u][qt][0e][9u][0t][eq][0u][9t][0i][qt][0e][9i][0t][eq][0i][9t]
[0eu][Et][e][uw][et][eE][eu][tw][ei][Et][e][iw][et][eE][ei][tw]
[eu][Et][e][uw][et][eE][eu][tw][ei][Et][e][iw][et][eE][iy][it]
[Eiqu][it][eu][uy][tu][ei][u][ty][iu][it][eu][iy][tu][ei][iu][ty]
[u][it][eu][uy][tu][ei][u][ty][iu][it][eu][iy][ot][ei][iu][ty]
[otuw][it][eu][uy][tu][ei][u][ty][iu][it][eu][iy][tu][ei][iu][ty]
[ou][it][eu][uy][it][eu][uy][t][iu][ty][et][Ei][ty][et][Ei][et]
[Eiqtu][Et][e][uw][Et][e][uw][qt][ei][tw][eq][0i][tw][eq][0i][9t]
[0u][qt][0e][9u][0t][eq][0u][9t][0i][qt][0e][9i][0t][eq][0i][9t]
[tu]e[0x][tu][ez]0[tu]e[itz]e[0l][it]e0[it]e
[ru]w[0l][ru][kw]0[lru]w[irz]w[0l][ikr]w0[ijr]w
[ekt]q8[ejt]q8[eht]q[eky]q8[ejy]q8[ejy]q
[HrW]0[7g][frW]07[rW]0[Wy]07[Wy]07[Wy]0
[gtu][ef][0d][ftu][eg][0h][tu]e[it]e0[it]e0[it]e
[fru]w0[gru]w0[hru]w[ijr]w0[hir]w0[gir]w
[eft][gq][8f][det][fq]8[det]q[esy]q8[aey]q8[esy]q
[arW][0s][7a][prW][0a]7[prW]0[OWy]07[Wy]07[Wy]0
[0estu]teu[pt]e[0etu][0et][0eit]t[0et]i[0ety]e[0eit]t
[9gruw]tfedu[ft]e[9ruw][9rtw][9irw]t[9erw]i[0tw]e[9irw]t
[8ehqu][gt][ef][du][ft][de][8eqsu][8aeqt][8eiqs][at][8epq][io][9pqrt][eo][8eiq][tu]
[07iuW][tu][ey][u][ty][et][07uWy][07tW][07irW][t][07erW][ei][08etW][eq][09irW]t
[0etu]teute[0etu][0et][0eit]t[0et]i[0ety]e[0eit]t
[9oruw][pt][ae][su][dt][ef][9gruw][9hrtw][9ijrw]t[9erw]i[0tw]e[9irw]t
[8eiqu]t[ep]u[at]e[8eqsu][8eqt][8deiq]t[8efq]i[9gqrt]e[8ehiq]t
[07fuW]teute[07uW][07tW][07iW]t[07eW]i[08et]e[9irW]t
[0aetuy][pt][aey][su][dit][esu][0aertuy]t[0epty]u[0aeity][pt]u[0aety]i[isu][0deioty][esu]i[0aeity]o[pt]
[9apruwy][pt][aey][su][dit][esu][9aruwy][9prtw][9airwy][pt][9aerwy][isu][0ditw][efsu][9agirwy][hpt]
[8aegquy][pt][aey][gsu][dijt][esu][8aegquy][8ekpqt][8aeiqy][pt][8aeqy][isu]j[9diqrt][eksu][8aeijqy]k[pt]j
[07aHuWy][pt][aey][gsu][dfit][esu][07auWy][07ptW][07aiWy][pt][07aeWy][isu][08deit][esu][9airWy][pt]
[0aetuy][pt][aey][su][dipt][esu]a[0aetuy]s[0ept][0adeity][pt]f[0aety]g[isu][0dehity][esu]g[0aeity]f[pt]
[9afruwy][pt][aey][su]d[dit][esu][9arsuwy][9prtw]a[9airwy]s[pt][9aerwy][isu]p[0ditw]a[esu][9aiprwy][pt]o
[8aequy]p[pt][aeoy][su]i[dit]o[esu][8aeiquy][8epqt]u[8aeiqy]i[pt][8aeqy][isu][9diqrt][esu][8aeiqy][opt]i
[07auWy]u[pt][aey][su][dit][esu][07auWy][07ptW][07aiWy][pt][07aeWy][isu][08deit][esu][9airWy][pt]
[0aetuy][pt][aey][su][dit][esu][0aeftuy][0ept][0aeijty][pt][0aekty][isu][0deilty][esu][0aeityz][pt]
[9akruwy][pt][aey]h[su][dit][esu]f[9aruwy][9prtw][9airswy][pt][9aerwy]a[isu][0ditw][esu]s[9airwy][pt]
[8aequy][pt][aey]p[su][dit][esu][8aequy]o[8epqt][8aeiqy][pt][8aeqy][isu][9diqrt][esu][8aeipqy][pt]
[07aOuWy][pt][aeOy][su][dit][esu][07auWy][07ptW][07aiWy][pt][07aeWy][isu][08deitu][esu][9airWy][pt]
[0aeOtuy][pt][aeOy][psu][dit][esu][0aetuy][0ept][0aeipty][pt][0aety][iosu][0deity][esu][0aeity][pt]
[9airuwy][pt][aey][su][ditu][esu][9aruwy][9prtw][9airwy][pt][9aerwy][isu][0ditw][esu][9airwy][pt]
[8aeiquy][ptu][aey][su][dity][estu][8aequy][8epqt][8aeiqry][pt][8aeqry][eisu][9diqrt][esu][8aeiqwy][pt]
[07aquWy][pt][aey][0su][dit][esu][07auWy][07ptW][07aiWy][pt][07aeWy][isu][08deit][esu][9airWy][pt]
[4ei]----[5or]-[4ei] 
[3uW] 0WrurW0ru--
[4ei]----[3uW]-[4ei] 
[5or] wryoyrwryo--
[4pt]----[5ay]-[4pt] 
[3Or] tyuioiu--
[4pt]----[3Or]-[4pt] 
[5ay] rtyuytr--
[4is]----[5do]-[4is] 
[3au]34567890qwq0-
[4is]----[3au]-[4is] 
[5do]uoppour--
[4gp]----[5ah]-[4gp] 
[3fO]-ruetwrqe0-
[4gp]----[3fO]-[4gp] 
[5ah] ertyuiopasdfgh
[ej] [tu] W [tu]w [tu] Q [tu]-
[ej] [iy] e [hiT]e [it] e [ir]-
[eg] [tu] W [ftu]w [tu] Q [tu]-
[eg] [iy]f[eg] [fiT][eg] [fit] [de] [irs]-
[es] [tu] W [tu]w [tu] Q [tu]-
[eg]f[diy]f[de]s[diT][es]a[ipt]a[es]d[fir]g 
ef [tu] W [tu]w [tu] Q [tu]-
[eg] [iy]hej[iT]ek[it] le [ir]z-
[6el] [6tu] W [tu][6w] [6tu] Q [6tu]1 
[2e] [2iy] e [iT][2e] [2it] e [2ir]4 
[6e] [6tu] W [tu][6w] [6tu] Q [6tu]1 
[2e] [2iy] e [iT][2e] [2it] e [2ir]4 
[6e]l [6tu] W [tu][6w]k[6tu] Q [6tu]1 
[2el] [2iy]kej[iT][2e]k[2it] je [2ir]h4 
[6eG] [6tu] W [tu][6w]h[6tu] Q [6tu]1 
[2e] [2iy] e [iT][2e] [2it] je [2ir]j4 
[6ej] [6tu]kWl[tu][6w]l[6tu] Q [6tu]1 
[2e] [2iy] e [iT][2e]z[2it] le [2ir]k4 
[6ek] [6tu] [jW] [tu][6w] [6tu] Q [6tu]1 
[2e] [2iy] e [iT][2e] [2it] e [2ir]4 
[6e] [6tu] W [tu][6w] [6tu] Q [6tu]1 
[2e] [2iy] e [iT][2e] [2it] e [2ir]4 
[6e] [6tu] W [tu][6w] [6tu] Q [6tu]1 
[2e] [2iy] e [iT][2e] [2it] e [2ir]4
]]
end

module['Creep'] = function()
	return [[
5 9 r w 9 r w 9 
t w 9 r w 9 r 9 
7 Q Y r Q Y r Q 
u r Q Y r Q Y Q 
[18] w u t w u t w 
i t w u t w u w 
[18] w Y t w Y t w 
i t w Y t w Y w 
5 9 r w 9 r w 9 
t w 9 r w 9 r 9 
7 Q Y r Q Y r Q 
u r Q Y r Q Y Q 
[18] w u t w u t w 
i t w u t w u w 
[18] w Y t w Y t w 
[(8wt]--y ppo I o 
5 9 r w 9 r w 9 
t w 9 [ry]y[wp] [9p] [ro] [9I] 
7 [QY] Y r Q Y r Q 
u r Q Y [rp] [Qp] [YI] [Qo] 
[18] [wu] u t w u t w 
i t wy[yu]y[tp] [wp] [uo]Iwo
[18] w Y t w Y t w 
1 8 2 [9y] [@p] [(p] [1I] [8o] 
5 [9y] r w 9 r w 9 
t w [9y] [ry] [wp] [9o] [rI] [9I] 
7 Q Y r Q Y r Q 
u r [Qp] [Yp] [rp] [Qp] [Yo] [Qa] 
[18] [wo] u t w u t w 
i t w [uo] [to] [wp] [uo] [wa] 
[18] [wo] Y t w Y t w 
1-2 [ro] [@ro] [ya] 4 [ya] 
5-9 [9wr]-9 [9wr] 9 
5-9 [9wro] [ro] [9ya] [9wr] [Y9a] 
7[rI][rI] 7 [(Qr]-7 [(Qr] 7 
7-[7ya] [(Qrya] [us] [7ya] [(Qrya] [7tp] 
[1ya]-8 [0wt]-8 [0wt] 8 
1-8 [0wt] [ro] [8tp] [0wrto] [8ya] 
1 [to] 8 [(wt]-8 [(wt] 8 
1----
5 9 r w 9 r w 9 
t w 9 r w 9 r 9 
7 Q Y r Q Y r Q 
u r Q Y r Q Y Q 
[18] w u t w u t w 
i t w u t w u w 
[18] w Y t w Y t w 
[(8wt]--y p o I o 
[5o] 9 r w 9 r w 9 
t w 9 [ry]y[wp] [9p] [ro] [9I] 
7I[QY] Y r Q Y r Q 
u r Q [Yp] [rp] [Qp] [YI] [Qo] 
[18] [wu] u t w u t w 
i t w [yu]y[tp] [wp]ou [wI]o
[18] w Y t w Y t w 
1 8 2 [9y] [@p] [(p] [1o] [8I]o
5 [9y] [ry] w 9 r w 9 
t w 9 [ry]y[wp]p[9o] r [9I]o
[7I] Q Y r Q Y r Q 
u r Q [Yp] [rp] [Qp] [Yo] [Qa] 
[18] [wo] u t w u t w 
i t w [uo] [to] [wp] [uo] [wa] 
[18] [wo] Y t w Y t w 
1-2 [ro] [@ro] [ya] 4 [ya] 
5-9 [9wr]-9 [9wr] 9 
5-9 [9wro] [ro] [9ya] [9wr] [Y9a] 
7[rI][rI] 7 [(Qr]-7 [(Qr] 7 
7-[7ya] [(Qrya] [us] [7ya] [(Qrya] [7tp] 
[1ya]-8 [0wt]-8 [0wt] 8 
1-8 [0wt] [ro] [8tp] [0wrto] [8ya] 
1 [to] 8 [(wt]-8 [(wt] [8dz] 
1 [sl] 2 [dz] @ [sl] 4-
[5hkzv]-9 [9wr]-9 [9wr] 9 
[5jb]-[9hv] [9wrkzGC]-[9dz] [9wrdz] [9kDZ] 
7 [GC] 7 [(QZCrkn]-[7GC] [rk(QGZC] 7 
7-7 [(Qr]-7 [(Qr] 7 
[1hlzv]-8 [0wt]-8 [0wt] 8 
[1jb]-[8hv] [0wtlGC]-8 [0wt] 8[DZ]
[1hDZ]-8 [(wt][gc][ghjc] 8 [(wt] 8[hv]
[Z1hlv]-2-[hv][@jlb]-4-
5-9 [9wr]-9 [9wr] 9[hv]
[5hkzv]-9 [9wr]-9 [9wr] 9 
7-7 [(Qr]-7 [(Qr] 7 
7-7 [(Qr]-7 [(Qr] 7[hv]
[1jlb]-8 [0wt]-8 [0wt] 8[hv]
[1hlv]-8 [0wt]-8 [0wt] 8 
1-8 [(wt]-8 [(wt] 8 
1--y p p-oI
[5o] 9 r w 9 r w 9 
t w 9y[ry]y[wp] [9p]or [9I]I
7 Q Y r Q Y r Q 
u r Q [Yp] [rp] [Qp] [Yo] [Qa] 
[18] [wo] u t w u t w 
i t w [uo] [to] [wp] [uo] [wa] 
[18] [wo] Y t w Y t w 
1-2 [ro] [@ro] [ya] 4 [ya] 
5-9 [9wr]-9 [9wr] 9 
5-9 [9wro] [ro] [9ya] [9wr] [Y9a] 
7[rI][rI] 7 [(Qr]-7 [(Qr] 7 
7-[7ya] [(Qrya] [us] [7ya] [(Qrya] [7tp] 
[1ya]-8 [0wt]-8 [0wt] 8 
1-8 [0wt] [ro] [8tp] [0wrto] [8ya] 
1 [to] 8 [(wt]-8 [(wt] 8 
1--o p o a 
[579wp] o
]]
end
module["Golden Hour"] = function()
	return [[
[Gp] [HS] [fk] [LS] [fk] [HS] [Gp] [HS] [fk] [LS]
[fk] [HS] [Gp] [HS] [fk] [LS] [fk] [HS] [Gp] [HS]
[fk] [LS] [fk] [HS] [fO] [aH] [Dk] [aL] [Dk] [aH]
[fO] [aH] [Dk] [aL] [Dk] [aH] [fO] [aH] [Dk] [aL]
[Dk] [aH] [fo] [aH] [Dk] [aL] [Dk] [aH] [fI] [Gp]
[jS] [kp] [jS] [Gp] [fI] [Gp] [jS] [kp] [jS] [Gp]
[fI] [Gp] [jS] [kp] [jS] [Gp] [fI] [Gp] [jS] [kp]
[jS] [Gp] [Du] [fO] [aG] [HO] [aG] [fO] [Du] [fO]
[aG] [HO] [aG] [fO] [Du] [fO] [aG] [HO] [aG] [fO]
[Du] [fO] [aG] [HO] [aG] [fO] [6O] [0O] [OT] [0O]
[OT] [0I] [6V] 0 T 0 T 0 [6O] [0O]
[OT] [0O] [OT] 0 [6O] [0O] [OT] [0O] [OT] 0
[%O] [(O] [Or] [(O] [Or] [(I] [%V] ( r (
r ( [%O] [(O] [Or] [(O] [Or] ( [5O] [(O]
[Or] [(O] [Or] ( [$O] [*O] [eO] [*O] [eO] [*I]
[$C] * e * e * [$O] [*O] [eO] [*O]
[eO] [*I] [$C] * e * e * [3O] [7O]
[OW] [7O] [OW] 7 [3DO] [7O] [OW] [7O] [OW] 7
[3fO] 7 [OW] 7 [OW] [7I] [3Gu] 7 [OW] 7
[aW] 7 [6eu] p S 0 T 0 T 0
[6e] 0 [ST] 0 [DpT] 0 [6efpS] 0 T 0
T 0 [6e] 0 [pST] 0 [fOT] 0 [%DOW] (
[rS] ( [aOr] ( [%aOW] ( r ( [Or] (
[%aDOWY] ( [rS] ( [aOr] ( [5aDowY] ( [rS] (
[aor] ( [$aIQ] [*p] e * e * [$Q] *
e * e * [$Q] * e * [eSu] *
[$aIQTu] * [eIp] * [eIO] * [%OtWY] [%W] [%W] [%OSTW]
[%W] [%W] [(fOuW] % [(W] % [(W] % [GIOstY] [6HLVx]
H k L k H [GTuW] H k L k
H [fGOS] H k L k H [GOTu] H k
L k H [6fHLS] [06DHWZ] [6kx] n [kx] n [kx]
[0t] n [kx] n [kx] [0t] n [kx] n [$CjQ]
b [Cj] b [Cj] [etu] b [Cj] b [Cj] [etu]
b [Cj] b [3HVxZ] f [GrWY] H [GrWY] f [03D]
f [GrWY] H [GrWY] f [aDO] f G H [aDGO]
f [DOrY] f G H [GOrY] f [3D] f G
H [03G] f [rWYZ] f G H [GrWY] f [$x]
f G H G f [%C] f G H G
f [6HLVx] H k L k H [GTuW] H k
L k H [fGOS] H k L k H [GOTu]
H k L k H [6fHLS] 6 e 6 [0DHWZ]
[6kx] 0 n t [kx] n [kx] n [kx] 6
n [kx] [0t] n [kx] 6 n [CejQtu] b [Cj]
b [Cj] b [Cj] b [Cj] [6] b [Cj] b
[3HVxZ] f G H [03G] f [DrWY] f G H
G f [aDO] f G H G f [DOrY] f
G H G f [3D] f [3G] H [03G] f
[DrWY] f G H G f [$d] f G [*$6HQ]
G f [%d] f G [(%HQW] G f [6eO] [*O]
[0OT] [eO] [0OT] [eI] [6eH] V * [0T] e [0T]
e [6eO] [*O] [0OT] [eO] [0OT] e [6eO] [*O] [0OT]
[eO] [0OT] e [%OW] [7O] [(Or] [OW] [(Or] [IW] [%HW]
V 7 [(r] W [(r] W [%OW] [7O] [(Or] [OW]
[(Or] W [5Ow] [7O] [(Or] [Ow] [(Or] w [$OQ] [6O]
[*eO] [OQ] [*eO] [IQ] [$GQ] C 6 [*e] Q [*e]
Q [$OQ] [6O] [*eO] [OQ] [*eO] [IQ] [$GQ] C 6
[*e] Q [*e] Q [03O] [%O] [7OW] [0O] [7OW] 0
[03DO] [%O] [7OW] [0O] [7OW] 0 [03fO] % [7OW] 0
[7OW] [0I] [03Gu] % [7OW] 0 [7aW] 0 [6u] p
S 0 e T e 0 [6] 0 [eSu] T
[Dep] 0 [6fpS] 0 e T e 0 [6] 0
[efp] T [eGO] 0 [%DO] ( [SW] r [aOW] (
[%aO] ( W r [OWY] ( [%aDOY] ( [SW] r
[aOW] ( [5DOY] ( [SW] r [aOW] ( [$aI] [*Ip]
Q e Q * [$] * Q e Q *
[$] * Q e [QSTu] * [$aITu] * [IpQT] e
[IOQT] [*Oru] [3] 7 0 W 0 7 [3] 7
0 W 0 7 [3] 7 0 W [0I] 7
[3u] 7 [0O] W [0a] 7 [6u] p S 0
e T e 0 [6] 0 [eSu] T [Dep] 0
[6fpS] 0 e T e 0 [6] 0 [efp] T
[eGO] 0 [%DO] ( [SW] r [aOW] ( [%aO] (
W r [OWY] ( [%aDOY] ( [SW] r [aOW] (
[5DOY] ( [SW] r [aOW] ( [$aI] [*Ip] Q e
Q * [$] * Q e Q * [$] *
Q e [QSTu] * [$aITu] * [IpQT] e [IOQT] *
[%OtY] [(W] [(W] [%OST] [(W] [(W] [(fOuW] % [(W] %
[(W] % [GIOstY] [6HLVx] H k L k H [GTuW]
H k L k H [fGS] H [kOS] L [fkS]
H [GOu] H [kTu] L [kOu] H [6fHLS] [0W] [0W]
[!*DHZ] [0W] [0W] [6kx] n [kx] 6 n [kx] [0e]
n [kx] 8 n [kx] [0e] n [kx] 8 n
[$CjQ] b [Cj] e b [Cj] t b [Cj] e
b [Cj] Q b [Cj] 8 b [3HVxZ] f G
H [03G] f [DrWY] f G H G f [aD]
f [aGO] H [aG] f [DOY] f [GrY] H [GOY]
f [3D] f G H [03G] f [rWYZ] f G
H G f [$x] f [$GQ] H [5G] f [%C]
f [%GW] H [%G] f [6HLVx] H k L [6ek]
H [GTuW] H k L k H [fGS] H [kOS]
L [fkS] H [GOu] H [kTu] L [kOu] H [6fHLS]
6 e 6 [0DHWZ] [6kx] 0 n t [kx] n
[kx] n [kx] 6 n [kx] [0t] n [kx] 6
n [Cejptu] b [Cj] b [Cj] [etu] b [Cj] b
[Cj] [Qtu] b [Cj] b [3HVxZ] f G H [03G]
f [DrWY] f G H G f [aD] f [aGO]
H [aG] f [DOY] f [GrY] H [GOY] f [3D]
f [3G] H [03G] f [DrWY] f G H G
f [$x] f G [*$6HQ] G f [%C] f G
[(%HQW] G f [6H] L x V * 0 W
T u [eOTu] [6eLS] [DZ] [0kn] Q e t [bj]
[03HV] [0rWY] [03] [DZ] [0frWxy] [CG] [6eH] L x V
[eOTu] [6eLS] [DZ] [0kn] Q r t [bej] [03H] k
x V [0rWY] [03] [0rWy] [eHTu] V f x [OS]
L [HrWY] V D Z [aI] k [Grwy] C d
z [IS] L p j [eGTu] C d z [OS]
L [0frw] x a k [fu] x h v [EGQT]
C P T I P [GI] S J G L
]]
end
module["Never Meant to Belong"] = function()
	return [[
[6rtu]--
[rtu]--[etu]--
[etu]--[5rtu]--
[rtu]--[etu]--
[etu]--[4rtu]--
[rtu]--[etu]--
[etu]--[3eru]--
[eru]--[ru]W----
klxz6--
6--
5--
5--
klxz4--
4--
3--
3--
klvx6--
Zx6--
Z [5x]--
Z x5--
c-[4x]--
z-l-k4-
j--h-[3G]--
g--f-3--
upah[6f]--
D-f6--
D-[5f]--
l--k-5H--
j--a-[4s]--
a-s4--
d-[3s]--
i--[3u]--
f--d-[6s]--
a-s--d-s6--
a-[5s]--
a-[5s]-
l-k-H-j-a-[4s]a
p--4--
3--
a--O--
[@r]--[9t]--
e--r--
t--[TW]--
y--[qu]--
i--[0I]--
o--p0--
o--[6P]--
[5p]--
i--o--[$u]--
O-p-a--
p-O p a [4s]--
O--i--
y--[7u]--
o-[3i]--
[3u]--
[6rtu]--
[rtu]--[etu]--
[etu]--[5rtu]--
[rtu]--[etu]--
[etu]--[4rtu]--
[rtu]--[etu]--
[etu]--[3eru]--
[eru]--[ru]W--
klxz6--
6--
5--
5--
klxz4--
4--
3--
3--
klvx6--
Z[6x]--
Z [5x]--
Z x5--
c-[4x]--
z-l-k4-
j--h-[3G]--
g--f-3--
upah[6f]--
D-f6--
D-[5f]--
l--k-5H--
j--a-[4s]--
a-s4--
d-[3s]--
i--[3u]--
f--d-[6s]--
a-s--d-s6--
a-[5s]--
a-s5-
l-k-H-j-a-[4s]a
p--4--
3--
a--O--
[@r]--[9t]--
e--r--
t--[TW]--
y--[qu]--
i--[0I]--
o--p0--
o--[6P]--
[5p]--
i--o--[$u]--
O-p-a--
p-O p a [4s]--
O--i--
y--[7u]--
o-[3i]--
[3u]--
]]
end

module['Moonlight Sonata 3rd Movement'] = function()
	local SHEET = [====[
!%[*%]0[!W]*[%0]W[!T]0[%W]T[!u]W[%T]u
[!O]T[%u]O[!S]u[%O]S[!f]O[%S]f[!*fHOS] [%fHOS] 
1%[%8]([1W]8[(%]W[1t]([%W]t[1Y]W[%t]Y
[1O]t[%Y]O[1s]Y[%O]s[1D]O[%s]D[18DHOs] [%DHOs] 
7*[%q]W[7T]q[%W]T[7i]W[%T]i[7O]T[%i]O
[7S]i[%O]S[7g]O[%S]g[7H]S[%g]H[7gHLS] [%gHLS] 
6*[6Q]e[6T]T[6I]p[6S]S[6G]j[6GLS] [6GLS] 
6*[06]w[6T]T[6u]o[6S]S[6f]h[6hLS] [6hLS] 
[%Hls] [OtW]H[Ot]H[PT]H[sY]H[Su]H[DI]H[sY]H
[DI]H[Su]H[Gp]H[fO]H[DI]H[Su]H[sY]H[pT]h
[OtW]H[Ot]H[Ot]H[PT]H[sY]H[Su]H[DI]H[sY]H
[DI]H[Su]H[Gp]H[fO]H[DI]H[Su]H[sY]H[pT]h
[OtW]H[pTW]h[OtW]H[pTW]h[OtW]H[pTW]h[OtW]H[pTW]h
[HOtW]-[%W]----
!%[*%]0[!W]*[%0]W[!T]0[%W]T[!u]W[%T]u
[!O]T[%u]O[!S]u[%O]S[!f]f[%H]L[!*fx] [%fx] 
^0[*w]T[^u]w[*T]u[^o]T[*u]o[^S]u[*o]S
[^f]o[*S]f[^h]S[*f]h[^L]f[*h]L[^fx] [*fx] 
5([(E]T[5Y]E[(T]Y[5P]T[(Y]P[5S]Y[(P]S
[5D]P[(S]D[5J]S[(D]J[5L]J[(D]S[5J]D[(S]P
[%a](7([%D](7(%(7([%a](7[(O]
[^o]O(P[*O]([^o](*(^([*o]([^D](*[(o]
[7P](7([7O](7(7([7O]([7D](7[(O]
[5a](5([5P](5(5([5P]([5D](5[(P]
[%a]([7DZ](%([7DZ](%([7DZ]([%ak]([7HO](
[^HO]([*ho](^([*ho](^([*ho]([^DZ]([*ho](
[7JP]([7HO](7([7HO](7([7HO]([7DZ]([7HO](
[5ak]([5JP](5([5JP](5([5JP]([5DZ]([5JP](
[$ls](%($(%([3LS]*%*3*%*
[3JP]k*Jk$JH*J[@ak]7$7@7$7@7$7
[2HO]7372737[!jp]636!636
[!ho]H^hH@hg^h[7HO]%@%7%@%7%@%
[!*36fjpS]----fGHjkLk
[jpTu]fGHjkLk[jpTu]fGHjkLk
[jpTu]fGH[jpTu]kLz[pTux]ZxZ[pTux]Lkj
[HY]aOaYaOa[JY]kSJkoJkSJkYJkSJkoJHSJ
[aHOu]-[!*36epTu]--uIOpaSa
puIO[*0ep]aSapuIO[*0ep]aSa
pu[*0eI]Opa[*0eS]apu[*0eI]Opa[*0eS]a
[*0ep]uIOpaSdfGHjkLzZ
[*fx]e0e*e0e[9HO]rqr9rqr
[(ak]rWr(rWr[@oTw](9(9(9(
[%OrW] [aWY] [aWY] [aWY] [aWY] [aWY] [EPY] [OrY] 
[(oTY] [DoTY] [DoTY] [DoTY] [DoTY] [DoTY] [DOrY] [DEPY] 
[%aDW] [aWY] [aWY] [aWY] [aWY] [aWY] [EPY] [OrY] 
[(oTY] [DoTY] [DoTY] [DoTY] [DoTY] [DoTY] [DOrY] [DEPY] 
[%aD] [aDrW] [aDrW] [aOrY] * [fSTW] [fSTW] [OSTu] 
( [aDrW] [aDrW] [aOrY] ( [DEPw] [DEPw] [EoPY] 
[%aO] [(%aDk] [(%aDk] [(%aDk] [(%aDk] [(%aDk] [(^JPS] [(7aHO] 
[(@*hoP] [(fhTx] [(fhTx] [(fhTx] [(fhTx] [(fhTx] [(DhrZ] [(EhLS] 
[%aHk] [(%aDk] [(%aDk] [(%aDk] [(%aDk] [(%aDk] [(^JPS] [(7aHO] 
[(@*hoP] [(fhTx] [(fhTx] [(fhTx] [(fhTx] [(fhTx] [(DhrZ] [(EhLS] 
[%aHkW] [HkrY] [HkrY] [krWZ] * [HLTu] [HLTu] [LTWx] 
( [HkrY] [HkrY] [krWZ] * [EhJY] [EhJY] [EJwZ] 
7 [DkOY] [DkOY] [HrYZ] * [jpSu] [jpSu] [fLTu] 
( [aHOY] [aHOY] [DkrY] ( [hoPT] [hoPT] [EJST] 
[%aH]W(W%W(W%W(W[%a]W([OW]
[%o]E(E[%DoT]E(E[%DoT]E(E[%DoT]E(E
[%r]OWD(W%W(W%W(W[%k]W([HW]
[%h]E(E[%hSZ]E(E[%hSZ]E(E[%hSZ]E(E
[%a]HWZ(W%W(W[%S]hEZ(E%E(E
[%a]HWZ(W%W(W[%S]hEZ(E%E(E
[%r][OW][(Y][OW][%r][OW][(Y][OW][%r][OW][(Y][OW][%r][OW][(Y][OW]
[%t][IQ][(Y][IQ][%t][IQ][(Y][IQ][%t][IQ][(Y][IQ][%t][IQ][(Y][IQ]
[!0TuW]%[*%]0[!W]*[%0]W[!T]0[%W]T[!u]W[%T]u
[!O]T[%u]O[!S]u[%O]S[!f]O[%S]f[!*fHOS] [%fHOS] 
1%[%8]([1W]8[(%]W[1t]([%W]t[1Y]W[%t]Y
[1O]t[%Y]O[1s]Y[%O]s[1D]O[%s]D[18DHOs] [%DHOs] 
7*[%q]W[7T]q[%W]T[7i]W[%T]i[7O]T[%i]O
[7S]i[%O]S[7g]O[%S]g[7H]S[%g]H[7gHLS] [%gHLS] 
6*[6Q]e[6T]T[6I]p[6S]S[6G]j[6GLS] [6GLS] 
6*[06]w[6T]T[6u]o[6S]S[6f]h[6hLS] [6hLS] 
[%Hls] [OtW]H[Ot]H[PT]H[sY]H[Su]H[DI]H[sY]H
[DI]H[Su]H[Gp]H[fO]H[DI]H[Su]H[sY]H[pT]h
[OtW]H[Ot]H[Ot]H[PT]H[sY]H[Su]H[DI]H[sY]H
[DI]H[Su]H[Gp]H[fO]H[DI]H[Su]H[sY]H[pT]h
[OtW]H[pTW]h[OtW]H[pTW]h[OtW]H[pTW]h[OtW]H[pTW]h
[HOtW]-[%W]----
!%[*%]0[!W]*[%0]W[!T]0[%W]T[!u]W[%T]u
[!O]T[%u]O[!S]u[%O]S[!f]f[%H]L[!*fx] [%fx] 
^0[*w]T[^u]w[*T]u[^o]T[*u]o[^S]u[*o]S
[^f]o[*S]f[^h]S[*f]h[^L]f[*h]L[^fx] [*fx] 
5([(E]T[5Y]E[(T]Y[5P]T[(Y]P[5S]Y[(P]S
[5D]P[(S]D[5J]S[(D]J[5L]J[(D]S[5J]D[(S]P
[%a](7([%D](7(%(7([%a](7[(O]
[^o]O(P[*O]([^o](*(^([*o]([^D](*[(o]
[7P](7([7O](7(7([7O]([7D](7[(O]
[5a](5([5P](5(5([5P]([5D](5[(P]
[%a]([7DZ](%([7DZ](%([7DZ]([%ak]([7HO](
[^HO]([*ho](^([*ho](^([*ho]([^DZ]([*ho](
[7JP]([7HO](7([7HO](7([7HO]([7DZ]([7HO](
[5ak]([5JP](5([5JP](5([5JP]([5DZ]([5JP](
[$ls](%($(%([3LS]*%*3*%*
[3JP]k*Jk$JH*J[@ak]7$7@7$7@7$7
[2HO]7372737[!jp]636!636
[!ho]H^hH@hg^h[7HO]%@%7%@%7%@%
[!*36fjpS]----fGHjkLk
[jpTu]fGHjkLk[jpTu]fGHjkLk
[jpTu]fGH[jpTu]kLz[pTux]ZxZ[pTux]Lkj
[HY]aOaYaOa[JY]kSJkoJkSJkYJkSJkoJHSJ
[aHOu]-[!*36epTu]--uIOpaSa
puIO[*0ep]aSapuIO[*0ep]aSa
pu[*0eI]Opa[*0eS]apu[*0eI]Opa[*0eS]a
[*0ep]uIOpaSdfGHjkLzZ
[*fx]e0e*e0e[9HO]rqr9rqr
[(ak]rWr(rWr[@oTw](9(9(9(
[%OrW] [aWY] [aWY] [aWY] [aWY] [aWY] [EPY] [OrY] 
[(oTY] [DoTY] [DoTY] [DoTY] [DoTY] [DoTY] [DOrY] [DEPY] 
[%aDW] [aWY] [aWY] [aWY] [aWY] [aWY] [EPY] [OrY] 
[(oTY] [DoTY] [DoTY] [DoTY] [DoTY] [DoTY] [DOrY] [DEPY] 
[%aD] [aDrW] [aDrW] [aOrY] * [fSTW] [fSTW] [OSTu] 
( [aDrW] [aDrW] [aOrY] ( [DEPw] [DEPw] [EoPY] 
[%aO] [(%aDk] [(%aDk] [(%aDk] [(%aDk] [(%aDk] [(^JPS] [(7aHO] 
[(@*hoP] [(fhTx] [(fhTx] [(fhTx] [(fhTx] [(fhTx] [(DhrZ] [(EhLS] 
[%aHk] [(%aDk] [(%aDk] [(%aDk] [(%aDk] [(%aDk] [(^JPS] [(7aHO] 
[(@*hoP] [(fhTx] [(fhTx] [(fhTx] [(fhTx] [(fhTx] [(DhrZ] [(EhLS] 
[%aHkW] [HkrY] [HkrY] [krWZ] * [HLTu] [HLTu] [LTWx] 
( [HkrY] [HkrY] [krWZ] * [EhJY] [EhJY] [EJwZ] 
7 [DkOY] [DkOY] [HrYZ] * [jpSu] [jpSu] [fLTu] 
( [aHOY] [aHOY] [DkrY] ( [hoPT] [hoPT] [EJST] 
[%aH]W(W%W(W%W(W[%a]W([OW]
[%o]E(E[%DoT]E(E[%DoT]E(E[%DoT]E(E
[%r]OWD(W%W(W%W(W[%k]W([HW]
[%h]E(E[%hSZ]E(E[%hSZ]E(E[%hSZ]E(E
[%a]HWZ(W%W(W[%S]hEZ(E%E(E
[%a]HWZ(W%W(W[%S]hEZ(E%E(E
[%r][OW][(Y][OW][%r][OW][(Y][OW][%r][OW][(Y][OW][%r][OW][(Y][OW]
[%t][IQ][(Y][IQ][%t][IQ][(Y][IQ][%t][IQ][(Y][IQ][%t][IQ][(Y][IQ]
[!iqTW]*[%q]W[!T]q[%W]T[!i]W[%T]i[!O]T[%i]O
[!S]i[%O]S[!g]O[%S]g[!H]S[%g]H[!*gHLS] [%gHLS] 
7*[%q]W[7T]q[%W]T[7i]W[%T]i[7O]T[%i]O
[7S]i[%O]S[7g]O[%S]g[7H]S[%g]H[7gHLS] [%gHLS] 
6*[6Q]e[6T]T[6I]p[6S]S[6G]j[6GjLS] [6GjLS] 
4*[4W]r[4T]T[4O]a[4S]S[4H]k[4HkLS] [4HkLS] 
[$GjLS]TeT[QS]TeTQTeT[pQ]Te[IT]
[iW]ITO[Ir]T[iW]TrTWT[ir]T[SW]Tr[iT]
[eO]TeT[eI]TeTeT[eI]T[eS]Te[IT]
[pq]TqT[Oq]TqTqT[Oq]T[qS]Tq[OT]
[pQ]SpS[IT]SpSISpS[eI]Sp[QS]
[OQ]SaS[Oq]SaSOS[aq]S[OT]Sa[qS]
[IW]SpS[IQ]SpSIS[pQ]S[IT]Sp[QS]
[IQ]d[pQ]d[Iy]dp[dQ][pQ]d[Qs]d[py]ds[dQ]
[ow]dad[9o]dadodad[7o]da[5d]
[5p]dsd[$p]dsdpd[$s]d[9p]ds[$d]
[6o]dad[5o]dadod[5a]d[9o]da[5d]
[$O]dad[4O]SaSOS[4a]S[*O]Sa[4S]
[$I]S[$p]S[6I]S[$p]S[2I]G[2p]G[$I]G[2p]G
[1I]G[DO]GIG[DO]GIG[1DO]G[@I]G[1DO]G
[!u]f[!S]f[3u]f[!S]f[6u]f[6S]f[!u]f[6S]f
[$Y]D[$S]D[6Y]D[$S]D[5Y]D[5S]D[^Y]D[5S]D
[%DsY]%%%[%O]%%%%%%%[%p]%[%O]%
[%eIT]%%%[%O]%[%I]%[%ruW]%%%[%I]%[%u]%
[%eQY]%%%[%u]%[%Y]%[%0TW]%%%[%Y]%[%T]%
[(%Qt]%%%%%%%[*%0T]%%%%%%%
[%8][%W][%Y]%[%H]%%%%%[%H]%[%j]%[%H]%
[%G]%[%GpS]%[%aDH]%[%GpS]%[%afO]%[%afO]%[%GpS]%[%afO]%
[%DIp]%[%DIp]%[%afO]%[%DIp]%[%OSu]%[%OSu]%[%DIp]%[%OSu]%
[%IsY]%%%%%%%[%STu]%%%%%%%
[%t]I%D%%%%%%%%%%[%STu]%%%
[%IsY]%%%[%IsY]%%%[%STu]%%%[%STu]%%%
[%t]I%D%%%%%%%%%%[%Tu]%[%S]%
[%IY]%[%s]%[%IY]%[%s]%[%Tu]%[%S]%[%Tu]%[%S]%
[%It]%[%D]%[%It]%[%D]%[6Tu]6[6S]6[6Tu]6[6S]6
[$epTY]----
[%OtWY]----
!%[*%]0[!W]*[%0]W[!T]0[%W]T[!u]W[%T]u
[!O]T[%u]O[!S]u[%O]S[!f]O[%S]f[!*fHOS] [%fHOS] 
1%[%8]([1W]8[(%]W[1t]([%W]t[1Y]W[%t]Y
[1O]t[%Y]O[1s]Y[%O]s[1D]O[%s]D[18DHOs] [%DHOs] 
7*[%q]W[7T]q[%W]T[7i]W[%T]i[7O]T[%i]O
[7S]i[%O]S[7g]O[%S]g[7H]S[%g]H[7gHLS] [%gHLS] 
6*[6Q]e[6T]T[6I]p[6S]S[6G]j[6GLS] [6GLS] 
6*[06]w[6T]T[6u]o[6S]S[6f]h[6hLS] [6hLS] 
[%Hls] [OtW]H[Ot]H[PT]H[sY]H[Su]H[DI]H[sY]H
[DI]H[Su]H[Gp]H[fO]H[DI]H[Su]H[sY]H[pT]h
[OtW]H[Ot]H[Ot]H[PT]H[sY]H[Su]H[DI]H[sY]H
[DI]H[Su]H[Gp]H[fO]H[DI]H[Su]H[sY]H[pT]h
[OtW]H[pTW]h[OtW]H[pTW]h[OtW]H[pTW]h[OtW]H[pTW]h
[HOtW]-[%W]----
*W0W[*O]W0W*W0W[*u]W0[TW]
[(t]TWY[QT]W[(t]WQW(W[Qt]W[(O]WQ[tW]
[0Y]W0W[0T]W0W0W[0T]W[0O]W0[TW]
[8u]W8W[8Y]W8W8W[8Y]W[8O]W8[WY]
[*u]W[0HO]W*W[0HO]W*W[0HO]W[*fu]W[0ST]W
[(ST]W[Qst]W(W[Qst]W(W[Qst]W[(HO]W[Qst]W
[0DY]W[0ST]W0W[0ST]W0W[0ST]W[0HO]W[0ST]W
[8fu]W[8DY]W8W[8DY]W8W[8DY]W[8HO]W[8DY]W
[7gi]W*W7W*W[6GI]Q*Q6Q*Q
[6DY]fQDf7DSQD[%fu]070%070%070
[5ST]0605060[$dy]969$969
[$st]S(sS%sP(s[3ST]*%*3*%*3*%*
[$69dIpQy]----paSdfGf
[deQy]paSdfGf[deQy]paSdfGf
[deQy]paS[deQy]fGh[ejQy]Hkj[ehQy]Gfd
[SW]uTuWuTu[DW]fIDftDfIDfWDfIDftDSID
[eSTu]-[$269eQy]--erTyuIu
yerT[$69y]uIuyerT[$69y]uIu
ye[$69r]Tyu[$69I]opa[$69S]dfG[$69h]H
[$jp]969$969[5ST]0^050^0
[%fu]0*0%0*0[%8Qt]%5%5%5%
[!*0T] [*uW] [*uW] [*uW] [*uW] [*uW] [(WY] [0TW] 
[%QtW] [OQtW] [OQtW] [OQtW] [OQtW] [OQtW] [0OTW] [(OWY] 
[!*Ou] [*uW] [*uW] [*uW] [*uW] [*uW] [(WY] [0TW] 
[%QtW] [OQtW] [OQtW] [OQtW] [OQtW] [OQtW] [0OTW] [(OWY] 
[!*Ou] [*0Ou] [*0Ou] [0TuW] $ [*IpQ] [*IpQ] [eIQT] 
% [*0Ou] [*0Ou] [0TuW] % [(8OY] [(8OY] [(tWY] 
[!*Tu] [*fOuW] [*fOuW] [*fOuW] [*fOuW] [*fOuW] [(DIWY] [0STuW] 
[%QstWY] [DIlsW] [DIlsW] [DIlsW] [DIlsW] [DIlsW] [fLSuW] [DGWYZ] 
[!*fHx] [*fOuW] [*fOuW] [*fOuW] [*fOuW] [*fOuW] [(DIWY] [0STuW] 
[%QstWY] [DIlsW] [DIlsW] [DIlsW] [DIlsW] [DIlsW] [fLSuW] [DGWYZ] 
[!*fHx] [HLTu] [HLTu] [fHOu] Q [IjLT] [IjLT] [GIjp] 
W [fHTu] [fHTu] [fOSu] Q [DHtY] [DHtY] [DOsY] 
0 [HSTW] [HSTW] [fOTu] $ [eGpQ] [eGpQ] [deIy] 
% [0fOW] [0fOW] [STuW] % [(DIQ] [(DIQ] [QstY] 
[!Su]*%*!*%*!*%*[!u]*%[*T]
[!t](%([!OQt](%([!OQt](%([!OQt](%(
[!0]T*O%*!*%*!*%*[!f]*%[*S]
[!s](%([!HIs](%([!HIs](%([!HIs](%(
[!u]S*H%*!*%*[!I]s(H%(!(%(
[!u]S*H%*!*%*[!I]s(H%(!(%(
[!0][*T][%W][*T][!0][*T][%W][*T][!0][*T][%W][*T][!0][*T][%W][*T]
[*7q][7T][!W][7T][*7q][7T][!W][7T][*7q][7T][!W][7T][*7q][7T][!W][7T]
[*6eQT]*[$Q]e[6T]Q[$e]T[6I]e[$T]I[6p]T[$I]p
[6S]I[$p]S[6G]p[$S]G[6j]S[$G]j[6GjLS] [$GjLS] 
%*[03]W[%T]0[3W]T[%u]W[3T]u[%O]T[3u]O
[%S]u[3O]S[%f]O[3S]f[%H]S[3f]H[%fHLS] [3fHLS] 
5 *0wET 5^!35 TuoPS 5^*0
w SfhJ[ELTuw]----
$ 68(Qe $61@$ etYIp $68(
QpsD[ejQtY]----
*OuO[TW]OuOTOuO[0T]Ou[*O]
[*Y]OIO[8Y]OIOYO[8I]O[WY]OI[8O]
[(T]OuO[*T]OuOTO[*u]O[TW]Ou[*O]
[0t]OIO[(t]OIOtO[(I]O[tW]OI[(O]
[0OTu]W0W[0HO]W0W0W0W[0fu]W0[STW]
[QST]WQW[Qst]WQWQW[Qst]W[HOQ]WQ[stW]
[0DY]W0W[0ST]W0W0W[0ST]W[0HO]W0[STW]
[8fu]W8W[8DY]W8W8W[8DY]W[8HO]W8[DWY]
[*GI]W[*fu]W[*LS]W[*fu]W[7GI]*[7gi]*[7LS]*[7gi]*
[6HO]*[6GI]*[6LS]*[6GI]*[4jp]*[4HO]*[4LS]*[4HO]*
[!$j]GSpITpITeQ*
eQ*6*QeTIpSGjGSp
[$2j]GdpIypIyeQ9
eQ969QeyIpdGjGdp
[!5L]JhfSPfSPouTE
uTEw0*0wETuoPSfhJLJf
[!%x]LHfSOfSOuSOu
TOuTWuTW0TW0*W0*
%6^78*9(0qQwWeEr
tTyYuiIoOpPasSdDfgGhH
[IjtW]kjkjkjkjkjkjkjkjkjkjkjkjkjkjkjk
H G f D G S s D 
p O I p u Y I T 
t Y e W Q e 0 ( 
Q * 8 (-6-%-
[5]----
[%]----
[!*]*%*!*%*!*%*[!u]*
%[*T][!t](%([!OQt](%([!OQt](%([!OQt](
%([!0]T*O%*!*%*!*%*[!f]*
%[*S][!s](%([!HIs](%([!HIs](%([!HIs](
%([!u]S*H%*!*%*[!I]s(H%(!(
%([!u]S*H%*!*%*[!I]s(H%(!(
%([!*%Y]SH[0u][OW][ST][fu][OW][ST][fu][HO][ST][fu][HO][LS][fu]
[HO][LS][fx][LS][HO][fu][LS][HO][fu][ST][HO][fu][ST][OW][fu][ST]
[OW][0u][ST][OW][0u][*T][OW][0u][*T][%W][0u][*T][%W][03][*T][%W]
[03][%W][!*]--[!*%3fHLS]--
[!*%3OSTu]
]====]
	return SHEET
end

module['Piano Man'] = function()
	local SHEET = [[
[8u]-
t u o s [8i]-t 
i s i [8o]-t o s 
o [pq]-[0o]-[9o]-[8o]--
o-[7o]-i--
u [6i] u t--5--
t-[4t]-t--
t [3t]-t y--
[29y]----r5--
o o [8o]-o--
7--i u [6i] 
u t--5--
e e [4e]--i 
i [5i]-u-t-[8t]-
t u o s [8i]-t i 
s i [8o]-t o s o [pq]-
0 o [9o]-[8o]-o-
o-[7o]-i-u-
[6i] u t--5--
t-[4t]-t-
t-[3t]--y y [2y]-
$-9-[5r]--
u i [8o]-o--
o [7o]--i u [6i]-
u-u-[5u]--
t-[4t]-t--u [5i]--
u t-[8t]----
u-o-s-
[ep]--p-[pw]--
a s [aQ]-p--
q----e--
p-[pw]--
a s [aQ]----
9-0-[$pQ]-[ow]-
a-d-[dq]-d-
d-[0f]-f-f-[9g]-
g-g-8h-h--
h [7h]-g--f 
[6g] f s--5----
[4p]-s--
s [3s]--d-[29d]-
$-9-5-f-
g-[8h]-h--
h [7h]-g--g [6g] f 
s--5--
o-[4p]-s-s-[5g]-
f-s-[8s]----
8-t i s i 
[8o]-t o s o [pq]-
[0o]-[9o]-[8o]--
o-[7o]-i--u [6i] 
u t--5--
t-[4t]-t--
t [3t]-t y--[29ey]----
[5r]--
o o [8o]-o--7--
i u i6 u t--
5--e e 
[4e]--i i [5i]-
u-t-[8t]-t u 
o s [8i]-t i s i o8-
t o s o [pq]-0 
o [9o]-[8o]-o-o-
[7o]-i-u-[6i] u 
t--5--
t-[4t]-t-t-[3t]--
y y [2y]-$-
9-[5r]--u i 
[8o]-o--o [7o]--
i u [6i]-u-
u-[5u]--t-t4-
t--u [5i]--
u t-[8t]----
u-o-s-[ep]--
p-5[pw]--
a s [aQ]-p--q----
e--
p-[5pw]--a s 
[aQ]----9-
0-[pQ]-[5ow]-a-
d-[dq]-d-d-[0f]-
f-f-[9g]-g-
g-[8h]-h--
h [7h]-g--f [6g] f 
s--5----
[4p]-s--s [3s]--
[dr]-d[29]-$-
9-5-f-g-
[8h]-h--h [7h]-
g--g [6g] f s--
5--o-p4-
s-s-[5g]-f-
s-[8s]----
8-t i s i [8o]-
t o s o [pq]-[0o]-
[9o]-[8o]-t u o s [8i]-
t i s i 8o-t 
o s o [pq]-[0o]-[9i]-
[8u]----
]]
	
	return SHEET
end

module['Drowning Love'] = function()
	local SHEET = [[
^qEtTO%WtTtW$WtT
tW!*tTYO^qEtTO%W
tTtW$WtTtW!*tTYO
EiPsSHWOsSsOQOsS
sO*TsSDHEiPsSHWO
sSsOQOsSsO*TsSDH
^qEtTO%WtTtW$WtT
GW!*tTYO[^iTW]qE[cgHLt]TO%W
tTtW$WtTtW!*tT*Q
[cE]lJiPsSHWOsSsOQOsS
sO*TsSDHEiPsSHWO
sSsOQOsSsO*TsSDH
[$iTW]
[iTW]*[iTW]$[TWY]
[*iTW] [$TWY]
[$iTW]-[$TW]
*[tW]-[*LTW]Jg-[4qt]TYOYT[HJtZ]T
YOYT[4qt]TYOYT[4P]YTtTY
[$iTW]
[iTW]*[iTW]$[TWY]
[*iTW] [$TWY]
[$iTW]-[$TW]
*[tW]-[*LTW]Jg-[4qt]TYOYT[HJtZ]T
YOYT[4qt]TYOYT[4P]YTtTY
[gOQS]
[gOS]T[gOS]Q[DOS]
[gOST] [DOQS]
[gOQS]-[OQS]
T[Os]-[cOST]LH-[4qs]SDHDS[HJsZ]S
DHDS[4qs]SD[Hl]DS[iJ]DSsSD
[gOQS]
[gOS]T[gOS]Q[DOS]
[gOST] [DOQS]
[gOQS]-[OQS]
T[Os]-[cOST]LH-[4qs]SDHDS[HJsZ]S
DHDS[4qs]SD[Hl]DS[iJ]DSsSD
[gOQS]
[gOS]T[gOS]Q[DOS]
[gOST] [DOQS]
[gOQS]-[OQS]
T[Os]-[cOST]LH-[4qs]SDHDS[HJsZ]S
DHDS[4qs]SD[Hl]DS[4Js]DS[4H]SD
[cE]lJiPsSHWOsSsOQOsS
sO*TsSDH[cE]lJiPsSHWO
sSsOQOsSsO*TsSDH
^qE[git]TO%Wt[HOT]tW$Wt[HOT]
tW!*t[HOT]YO^qE[git]TO%W
t[HOT]tW[$]----
[DT]Pis-PsS-W-
DSis-Ps[GY]--
[%D]SPis-PsS-q-
DSis-PsO Dgs-
[^D]Pis-PsS-q-
lgDs-Ps[gO]--
[%D]SPis-Ps[Oq]-- D
s-Ps----
[*Q]WT[fGkY]uO[7a]Ou[3S]Ou[6D]aO[3f]
[3a]O[%G]aO[@H]aO[*]WT[fGkY]uO[7a]O
u[3S]Ou[6D]aO[3f][3a]O[%G]aO[@D]aO
[!*]D[%f]k[!f]a[7]a[$f]H[7f]a[6j]f[3a]H
[6f]a[3G]D[7a]H[3D]a[!*Z]k[%H]x[!k]H[7C]k
[$H]V[7k]H[6x]k[3f]x[6k]f[3x]k[7f]x[3k]f
[!*]W[%T]Y[!u]a[7]W[$Y]u[7Y]r[6]0[3Y]u
[6Y]r[3]u[7Y]u[3O]a[!*]W[%T]Y[!u]a[7]W
[6Y]u[7Y]r[6]e[3Y]u[6Y]r[03]u[7Y]u[0O]a
[!*]O[%S]D[!f]k[7]O[$D]f[7D]a[6]u[3D]f
[6D]a[03]u[7D]f[0H]k[!*]O[%S]D[!f]k[7a]H
[$Z]x[7Z]k[6fGHS]----
]]
	return SHEET
end

return module
